#!/bin/sh

# Baseline Distro packages go here

set -x
set -e
                                                                                                                      
apt-get update                                                                                                        
apt-get install git # ...
