#!/bin/sh
set -x
set -e

# Git-based cabal source files

export HOME=/src

export PATH=/src/.cabal/bin:$PATH
cabal update

cd /src

get () {  
	git clone https://github.com/anchor/$1.git  
} 

get haskell_repo_one
get haskell_repo_two

cd /

find /src

cabal install -j \
	/src/haskell_repo_one \
	/src/haskell_repo_two 
